# Generated by Django 3.1.7 on 2021-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.CharField(max_length=20, verbose_name='Тип телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='telephone',
            name='telephone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='telephone',
            name='type_number',
            field=models.ManyToManyField(related_name='type_num', to='accounts.TypeNumber', verbose_name='Тип телефона'),
        ),
    ]
