# Generated by Django 3.1.7 on 2021-03-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210327_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=30, verbose_name='Область')),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_country',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=30, verbose_name='Город')),
                ('area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.area', verbose_name='Область')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country', verbose_name='Страна'),
        ),
    ]
