# Generated by Django 3.1.7 on 2021-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userlocation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='entrance',
            field=models.SmallIntegerField(blank=True, max_length=50, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='floor',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='house_number',
            field=models.CharField(default=1, max_length=10, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='room',
            field=models.SmallIntegerField(blank=True, max_length=500, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='street',
            field=models.CharField(default=1, max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
