# Generated by Django 3.1.7 on 2021-03-30 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20210330_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=20, verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Номер счета')),
                ('BIK', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')], verbose_name='БИК')),
                ('bank_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankname', verbose_name='Банк')),
                ('currency', models.ManyToManyField(related_name='currency_score', to='accounts.Currency', verbose_name='Валюта счета')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
