# Generated by Django 3.1.7 on 2021-03-30 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bankname_currency_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='BIK',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$')], verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{20}$')], verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='house_number',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^\\d{1,1000}$')], verbose_name='Номер дома'),
        ),
    ]
