# Generated by Django 3.1.7 on 2021-03-30 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210330_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='house_number',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^\\d{1,4}[/]{1,4}$')], verbose_name='Номер дома'),
        ),
    ]
