# Generated by Django 3.1.7 on 2021-03-30 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210330_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='SWIFT-код')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='BIK',
        ),
        migrations.AddField(
            model_name='score',
            name='bik',
            field=models.CharField(default=1, max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$')], verbose_name='БИК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='correspondent_account',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{20}$')], verbose_name='Корр.счет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='inn',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='kpp',
            field=models.CharField(default=1, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$')], verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='building',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='edifice',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='entrance',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='house_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,5}(([/]\\d{1,5})|[a-z,а-я])?$')], verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='room',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='score',
            name='swift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.swift', verbose_name='SWIFT-код'),
        ),
    ]
