# Generated by Django 3.1.7 on 2021-03-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210330_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='building',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='edifice',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='entrance',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='room',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баланс')),
                ('score_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='accounts.score', verbose_name='Счет')),
            ],
        ),
    ]
