# Generated by Django 3.1.7 on 2021-04-01 19:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20210331_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$')], verbose_name='Процентная ставка')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назначение кредита')),
                ('sum_credit', models.PositiveIntegerField(verbose_name='Сумма кредита')),
                ('beginning_date', models.DateField(auto_now=True, verbose_name='Дата начала кредита')),
                ('deadline', models.PositiveSmallIntegerField(max_length=3, verbose_name='Срок кредита')),
                ('interest_rate', models.ManyToManyField(related_name='credit_interestet_rate', to='accounts.InterestRate', verbose_name='процентная ставка')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кредит клиента')),
            ],
        ),
    ]
