# Generated by Django 3.1.7 on 2021-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_credit_interestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия кредита'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='interest_rate',
            field=models.ManyToManyField(related_name='credit_interest_rate', to='accounts.InterestRate', verbose_name='процентная ставка'),
        ),
    ]
