# Generated by Django 3.1.7 on 2021-04-01 20:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20210401_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='loan_credit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток по кредиту'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='rate',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,2}$')], verbose_name='Процентная ставка'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.PositiveIntegerField(verbose_name='Платеж')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments', to='accounts.credit', verbose_name='кредит')),
            ],
        ),
    ]
