# Generated by Django 3.1.7 on 2021-04-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210401_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rate', to='accounts.currency', verbose_name='Валюта')),
            ],
        ),
    ]
