# Generated by Django 3.1.7 on 2021-04-07 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Тип платежной системы')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^\\d{16,18}$')], verbose_name='Номер карты')),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')], verbose_name='Код безопасности')),
                ('date', models.DateField(verbose_name='Срок действия')),
                ('paymentsystem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paymentsystem_card', to='accounts.paymentsystem', verbose_name='тип платежной системы')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_card', to='accounts.score', verbose_name='банковская карта')),
            ],
        ),
    ]
