# Generated by Django 3.1.7 on 2021-04-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210408_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='paymentsystem',
        ),
        migrations.AddField(
            model_name='card',
            name='paymentsystem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='paymentsystem_card', to='accounts.paymentsystem', verbose_name='тип платежной системы'),
            preserve_default=False,
        ),
    ]
