# Generated by Django 3.1.7 on 2021-04-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210412_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default=1, max_length=5, verbose_name='Сивол валюты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='score_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_balance', to='accounts.score', verbose_name='Счет'),
        ),
    ]
