# Generated by Django 3.1.7 on 2021-04-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_auto_20210412_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_credit', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
    ]
