# Generated by Django 3.1.7 on 2021-04-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_typecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='card', to='accounts.typecard', verbose_name='Тип карты'),
            preserve_default=False,
        ),
    ]
