# Generated by Django 3.1.7 on 2021-04-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210418_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='loan_credit',
        ),
    ]
