# Generated by Django 3.1.7 on 2021-04-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210418_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения кредита')),
                ('interest_rate_mounth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процентная ставка за месяц')),
                ('mounthly_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ежемесячный платеж')),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общая задолженность')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оплачено')),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='accounts.credit', verbose_name='Кредит')),
            ],
        ),
    ]
