# Generated by Django 3.1.7 on 2021-04-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_creditinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinfo',
            name='interest_rate_mounth',
        ),
    ]
