# Generated by Django 3.1.7 on 2021-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_creditinfo_interest_rate_mounth'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinfo',
            name='interest_rate_mounth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процентная ставка за месяц'),
        ),
    ]
