# Generated by Django 3.1.7 on 2021-04-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_creditinfo_interest_rate_mounth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfo',
            name='interest_rate_mounth',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True, verbose_name='Процентная ставка за месяц'),
        ),
    ]
