# Generated by Django 3.1.7 on 2021-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210420_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfo',
            name='mounthly_payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ежемесячный платеж'),
        ),
    ]
