# Generated by Django 3.1.7 on 2021-04-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210421_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='credit',
            name='interest_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='credit_interest_rate', to='accounts.interestrate', verbose_name='процентная ставка'),
            preserve_default=False,
        ),
    ]
