# Generated by Django 3.1.7 on 2021-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210421_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinfo',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Осталось заплатить'),
        ),
    ]
