# Generated by Django 3.1.7 on 2021-04-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_creditinfo_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfo',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Оплачено'),
        ),
    ]
