# Generated by Django 3.1.7 on 2021-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210422_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfo',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Оплачено'),
        ),
    ]
