# Generated by Django 3.1.7 on 2021-04-22 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210422_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfo',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Оплачено'),
        ),
    ]
