# Generated by Django 3.1.7 on 2021-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210422_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='sum_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма кредита'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Платеж'),
        ),
    ]
