# Generated by Django 3.1.7 on 2021-04-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210422_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер платежа')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('mounthly_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ежемесячный платеж')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Осталок кредита')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments_info', to='accounts.credit', verbose_name='Информация о платежах')),
            ],
        ),
    ]
