# Generated by Django 3.1.7 on 2021-05-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_paymentsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип счета')),
            ],
        ),
        migrations.RemoveField(
            model_name='credit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='credit',
            name='score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_credit', to='accounts.score', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='paymentsinfo',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments_info', to='accounts.credit', verbose_name='Кредит'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='currency',
        ),
        migrations.AddField(
            model_name='score',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_score', to='accounts.currency', verbose_name='Валюта счета'),
        ),
        migrations.AddField(
            model_name='score',
            name='type_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc', to='accounts.typescore', verbose_name='Тип счета'),
        ),
    ]
