# Generated by Django 3.1.7 on 2021-05-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210501_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='score_card', to='accounts.score', verbose_name='Счет'),
        ),
    ]
